#' Toy tasks generated by \code{\link{generate_toy_datasets}}
#'
#' \code{
#'   toy_tasks <- dyntoy::generate_toy_datasets(num_replicates = 2); devtools::use_data(toy_tasks, overwrite=TRUE)
#' }
#'
#' @format TODO
"toy_tasks"
